version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  research-deck:
    build: .
    env_file:
      - .env
    depends_on:
      - ollama
    environment:
      - USE_OPENAI=${USE_OPENAI}        
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - OLLAMA_MODEL=deepseek-r1
      # - OLLAMA_BASE_URL=http://ollama:11434
      # - SUPABASE_URL=${SUPABASE_URL}
      # - SUPABASE_KEY=${SUPABASE_KEY}
      # - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run app.py

volumes:
  ollama-data:
