services:
  app:
    build: .
    container_name: research-deck
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false